/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Connection config mirrored across the napi boundary.
 *
 * Field-name parity with `agentic_flow_quic::types::ConnectionConfig`
 * (snake_case in Rust → camelCase in JS via `#[napi(object)]`).
 */
export interface ConnectionConfig {
  serverName: string
  /** Milliseconds; mapped to `max_idle_timeout_ms` upstream. */
  maxIdleTimeoutMs: number
  maxConcurrentStreams: number
  enable0Rtt: boolean
}
/**
 * `quinn::ConnectionStats` snapshot returned by [`stats`].
 *
 * Field-name parity is informed by `quinn::ConnectionStats` but
 * flattened: we expose RTT (µs) + bytes counters + congestion window +
 * lost packets, which is what federation health checks read. Add more
 * later if a real consumer asks.
 */
export interface ConnectionStats {
  rttUs: number
  bytesSent: number
  bytesReceived: number
  /** Current congestion window estimate (bytes). */
  congestionWindow: number
  /** Cumulative lost packets observed by the local quinn instance. */
  lostPackets: number
}
/**
 * Aggregated pool stats across every cached `QuicClient`. Field
 * names mirror `agentic_flow_quic::types::PoolStats` so JS callers can
 * shape-check by key.
 */
export interface PoolStats {
  active: number
  idle: number
  totalCreated: number
  totalClosed: number
  currentStreams: number
}
/**
 * Open a new QUIC connection (or reuse a pooled one) and return an
 * opaque `connId`. The `quinn::Connection` value is held in the
 * registry — callers address every later operation by `connId`.
 *
 * `addr` accepts any `SocketAddr`-parsable string (`"host:port"` or
 * `"ip:port"`). The SNI in `config.server_name` is what the upstream
 * `QuicClient` uses for TLS verification.
 */
export declare function connect(addr: string, config: ConnectionConfig): Promise<number>
/**
 * Send raw bytes as a `QuicMessage` over a fresh `open_bi()` stream
 * on the connection identified by `conn_id`.
 *
 * `message_type` defaults to `Custom(binary)` semantics — we map
 * the string to the upstream `MessageType` enum (`task` →
 * `MessageType::Task`, `result` → `Result`, …; anything else
 * becomes `MessageType::Custom(<string>)`).
 */
export declare function send(connId: number, bytes: Buffer, messageType?: string | undefined | null): Promise<void>
/**
 * Close one connection. The underlying `QuicClient` (and its endpoint)
 * stays alive — call [`close_all`] to drop everything.
 */
export declare function close(connId: number): Promise<void>
/**
 * Drain every connection + cached client. Servers are NOT touched
 * here — `server::close` (if/when added) covers them. Today the
 * Phase-1 surface doesn't include a `closeServer`; callers shut down
 * the whole process to release server endpoints.
 */
export declare function closeAll(): Promise<void>
/** Snapshot `connection.stats()` for one connection. */
export declare function stats(connId: number): Promise<ConnectionStats>
/**
 * Aggregate pool stats across every cached client. Sums the upstream
 * `PoolStats` from each — gives federation observability a single
 * number per metric.
 */
export declare function poolStats(): Promise<PoolStats>
/**
 * Inbound message payload pushed to the JS callback. Field-name parity
 * with the JS-side `AgentMessage` shape (post-loader normalisation):
 *   - `address` — peer `host:port`
 *   - `messageId` — upstream `QuicMessage.id` (uuid)
 *   - `messageType` — upstream `MessageType` flattened to string
 *   - `payload` — raw bytes (the upstream `QuicMessage.payload`)
 */
export interface InboundMessage {
  address: string
  messageId: string
  messageType: string
  payload: Buffer
}
/**
 * Bind a server on the given port and start accepting connections.
 *
 * `on_message` is called for every received `QuicMessage`. It runs on
 * a libuv worker — the napi-rs `ThreadsafeFunction` machinery handles
 * the tokio-thread → libuv hop.
 *
 * Returns a `serverHandle` (u32). Server shutdown is not part of the
 * Phase-1 surface — call `closeAll()` to drop client state; servers
 * die with the process. A `closeServer(handle)` can be added later
 * without breaking the contract.
 */
export declare function listen(port: number, config: ConnectionConfig, onMessage: (...args: any[]) => any): number
/**
 * Return the actual `host:port` the server bound to. Useful when
 * `listen(0, ...)` was used to let the OS pick a free port — the caller
 * can then `connect()` to the returned address.
 *
 * Errors if `server_id` doesn't exist in the registry or if the
 * underlying `QuicServer::local_addr()` fails (e.g. endpoint closed).
 */
export declare function getLocalAddr(serverId: number): string
