#!/usr/bin/env node
/**
 * Build CJS wrappers for ESM modules
 *
 * Creates .cjs files that re-export ESM modules for CommonJS compatibility.
 * This is safe because our entry points contain no top-level await.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const distDir = path.join(__dirname, '..', 'dist', 'src');

// Entry points that need CJS wrappers
const entryPoints = [
  { esm: 'index.js', cjs: 'index.cjs' },
  { esm: 'controllers/index.js', cjs: 'controllers/index.cjs' },
  { esm: 'backends/index.js', cjs: 'backends/index.cjs' },
  { esm: 'security/index.js', cjs: 'security/index.cjs' }
];

// CJS wrapper template
const createWrapper = (esmPath) => `/**
 * CommonJS wrapper for ESM module
 * Auto-generated by scripts/build-cjs.js
 */
const mod = require('./${esmPath}');
module.exports = mod;
`;

console.log('Building CJS wrappers...');

for (const { esm, cjs } of entryPoints) {
  const esmFile = path.join(distDir, esm);
  const cjsFile = path.join(distDir, cjs);

  // Check if ESM file exists
  if (!fs.existsSync(esmFile)) {
    console.warn(`Warning: ESM file not found: ${esm}`);
    continue;
  }

  // Create CJS wrapper
  const wrapper = createWrapper(esm);
  const cjsDir = path.dirname(cjsFile);

  // Ensure directory exists
  if (!fs.existsSync(cjsDir)) {
    fs.mkdirSync(cjsDir, { recursive: true });
  }

  fs.writeFileSync(cjsFile, wrapper, 'utf8');
  console.log(`✓ Created ${cjs}`);
}

console.log('CJS wrappers built successfully!');
